### ISSUE TITLE
Separating the Spec

### ISSUE THREAD

**Issue by rbarden** [traindown/traindown#4]
I think it might be beneficial to move the spec itself to a new repo to help facilitate versioning and keep it separate from general website changes. Especially with the change of spec coming from #3 it might help at release time. Just a thought!

**Comment by scottt2** [comment]
@rbarden Totally agree. I will do that by this weekend. Thanks for partnering on all this stuff. Digging your contributions.

**Comment by scottt2** [comment]
We now have a new repo here: https://github.com/traindown/spec

Mmmm, new repo smell!

I also added a little helper to pull the spec into the public site during build so we are always in sync.

Thanks for the suggestion!
